# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Know Yoga
email: yo@knowyo.ga
description: > # this means to ignore newlines until "baseurl:"
  no yoga, no peace
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://knowyo.ga" # the base hostname & protocol for your site
twitter_username: knowyoga
github_username:  energy7

# Build settings
markdown: kramdown
